### ISSUE TITLE
Can't download dictionaries/models

### ISSUE THREAD

**Issue by ryanfb** [OpenPhilology/nidaba#1]
When I run `python setup.py download`, I get an `invalid command` error:
```
python setup.py download
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'download'
```
Additionally, trying to download these dependencies manually, accessing <http://l.unchti.me/nidaba/MANIFEST> results in a 404 not found error.

**Comment by mittagessen** [comment]
I am sorry my server got hacked and I haven't gotten around to fix everything yet. I'm going out on a limb here why the download command isn't recognized but I assume some python API changed again. As I am currently rewriting most of the task stuff and consequently have to refactor almost all of the tests it is probably not worth the trouble to fix this. On the bright side the stuff you want to download is only required for the tests anyway.

**Comment by mittagessen** [comment]
pbr seems to be the issue here, overwriting the cmdclass of setuptools without carrying over anything previously defined there. I'll look into it.

**Comment by ryanfb** [comment]
I'll give it a go without the tests - just wanted to make sure I had a working environment/prerequisites before jumping in too deep. Thanks!

**Comment by mittagessen** [comment]
I return from the mess that is python packaging with a solution. The latest release should have a working download command now.
