### ISSUE TITLE
File required for tests doesn't exist anymore

### ISSUE THREAD

**Issue by illusionww** [OpenPhilology/nidaba#21]
From docs:
> Per default no dictionaries and OCR models necessary to runs the tests are installed. To download the necessary files run:
> 
> $ python setup.py download
> Afterwards, the test suite can be run:
> 
> $ python setup.py nosetests

`python setup.py download` tries to load archive [http://l.unchti.me/nidaba/tests.tar.bz2](http://l.unchti.me/nidaba/tests.tar.bz2), but the link is broken

**Comment by illusionww** [comment]
Is there another way to obtain the archive?

**Comment by mittagessen** [comment]
Sorry for the delay. It should be fixed now, although admittedly the test suite is in a sorry state. As most functionality is dependent on external library and testing celery tasks is nigh impossible the tests mostly check for proper set up of plugins and such.
