### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Arithmeticus** [OpenPhilology/nidaba#23]
When running python setup.py download I get the following syntax error 4 times:

```
creating /home/joel/OCR/nidaba/.eggs/linecache2-1.0.0-py2.7.egg
Extracting linecache2-1.0.0-py2.7.egg to /home/joel/OCR/nidaba/.eggs
  File "/home/joel/OCR/nidaba/.eggs/linecache2-1.0.0-py2.7.egg/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax
```

**Comment by mittagessen** [comment]
That is one of the dependencies pulled in by setuptools. It doesn't seem to interfere with downloading the test data.  Unfortunately, the tests are broken and have been for a long time as it is more or less impossible to build unit tests for complex subclassing celery tasks and most of the bugs happen in the code I'd have to mock away in any case anyway.
