### ISSUE TITLE
cannot install with python 3.7

### ISSUE THREAD

**Issue by yurj** [OpenPhilology/nidaba#26]
```
  Building wheel for pyxDamerauLevenshtein (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/nidaba/nidaba/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-caa2lwvy/pyxDamerauLevenshtein/setup.py'"'"'; __file__='"'"'/tmp/pip-install-caa2lwvy/pyxDamerauLevenshtein/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wc90vya7
       cwd: /tmp/pip-install-caa2lwvy/pyxDamerauLevenshtein/
```

[...]

```
/home/nidaba/nidaba/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  pyxdameraulevenshtein/pyxdameraulevenshtein.c: In function ‘__Pyx_GetException’:
  pyxdameraulevenshtein/pyxdameraulevenshtein.c:5209:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
       tmp_type = tstate->exc_type;
```
====

Any idea?

**Comment by rjendoubi** [comment]
For what it's worth, I was able to build / install with Python 3.6.9, but then `nidaba_mkdict` failed due to use of the `unichr` builtin.

Conversely, now when setting up under Python 2.7.17 the `kraken` deps fail to install, complaining that they need >=3.6.

Can this issue be widened to address version support in general? Given [how important it is to the authors not to break backwards compatibility](https://openphilology.github.io/nidaba/index.html#contributing), what is the best way to move the project forward to a version of Python that's supported?

**Comment by savasy** [comment]
I have the same problem with the one @yurj @yurj  has
I could not install, I always get error as follows*, even I could install pyxDamerauLevenshtein separately

``
  Failed building wheel for pyxDamerauLevenshtein
  Running setup.py clean for pyxDamerauLevenshtein
Failed to build pyxDamerauLevenshtein
``

**Comment by mittagessen** [comment]
* Savaş Yıldırım :: 2020-04-16 15:47 Thu:
> I have the same problem with the one @yurj @yurj  has
> I could not install, I always cannot install pyxDamerauLevenshtein, even I could install pyxDamerauLevenshtein separately

Sorry nidaba is severely out of date and shouldn't be used anymore. I'm
fairly sure that even if you got it installed it wouldn't work as it
makes heavy use of the celery canvas tools which the developers were
breaking constantly. Depending on your use case something like the ocr-d
tools or escriptorium might replace nidaba.

**Comment by savasy** [comment]
Hi @mittagessen ,
it is very kind of you, thank you I give it a try for ocr-d and escriptorium
thanks
