### ISSUE TITLE
pip install . problem

### ISSUE THREAD

**Issue by sonofmun** [OpenPhilology/nidaba#3]
When installing with `pip install .`, I get the following error message:

```
Downloading/unpacking pyxDamerauLevenshtein==1.3.1 (from nidaba==0.3.14)
  Downloading pyxDamerauLevenshtein-1.3.1.tar.gz (51kB): 51kB downloaded
  Running setup.py (path:/cluster/home/mmunso01/envs/nidaba/build/pyxDamerauLevenshtein/setup.py) egg_info for package pyxDamerauLevenshtein
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/cluster/home/mmunso01/envs/nidaba/build/pyxDamerauLevenshtein/setup.py", line 28, in <module>
        import numpy
    ImportError: No module named numpy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/cluster/home/mmunso01/envs/nidaba/build/pyxDamerauLevenshtein/setup.py", line 28, in <module>

    import numpy

ImportError: No module named numpy

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /cluster/home/mmunso01/envs/nidaba/build/pyxDamerauLevenshtein
Storing debug log for failure in /cluster/home/mmunso01/.pip/pip.log
```

By running `pip install numpy` first and then running `pip install .`, I was able to overcome this problem.  I also had this problem with PyTables so it could be that pyxDamerauLevenshtein needs to be detached and installed later (or numpy detached and installed earlier).

**Comment by mittagessen** [comment]
This is an issue with how pip install python packages (setup.py is executed to get the dependencies but requires numpy which isn't installed yet). I'll remove pyxDamerauLevenshtein and exchange it with pure python code which is significantly slower but still reasonably fast.

**Comment by sonofmun** [comment]
Or you could just ask the users to type `pip install numpy==???` and 
then `pip install .`

On 19.05.2015 10:05, mittagessen wrote:
>
> This is an issue with how pip install python packages (setup.py is 
> executed to get the dependencies but requires numpy which isn't 
> installed yet). I'll remove pyxDamerauLevenshtein and exchange it with 
> pure python code which is significantly slower but still reasonably fast.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenPhilology/nidaba/issues/3#issuecomment-103390524>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by mittagessen** [comment]
I created a pull request upstream that corrects the issue. Let's hope it get merged quickly.

**Comment by mittagessen** [comment]
Merged and version-bumped. Bumped nidaba up to 0.3.15 solving this bug.
