### ISSUE TITLE
Errors with Kraken

### ISSUE THREAD

**Issue by sonofmun** [OpenPhilology/nidaba#6]
When I use the following command:

    nidaba batch -b otsu -l tesseract -o kraken:grc_teubner -p spell_check:polytonic_greek -- /cluster/tufts/perseus_ocr/nidaba/teubner/ammonius_1966/*.tif

I get the following error showing up in the celery log for every page, i.e., every page fails with the same error

```
[2015-08-13 10:32:52,073: ERROR/MainProcess] Task nidaba.ocr.kraken[00db4d89-a411-4098-9036-9865acabe112] raised unexpected: AttributeError("'NoneType' object has no attribute 'predictString'",)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 81, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 123, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 132, in rpred
    pred = network.predictString(line)
AttributeError: 'NoneType' object has no attribute 'predictString'
```

nidaba.yaml looks like this:

```
# The home directory for Iris to store files created by OCR jobs. For example,
# tifs, jp2s, meta.xml, and abbyy file downloaded from archive.org are stored
# here. Each new job is automatically placed in a uniquely named directory.
storage_path: /cluster/tufts/perseus_ocr/nidaba/OCR/

# URL to the redis database. May be shared with celery.
redis_url: 'redis://127.0.0.1:6379'

# Spell check configuration. Dictionaries are kept on the common medium (i.e.
# at STORAGE_PATH/tuple[0]/tuple[1]). Each spell checker requires a list of
# valid words ('dictionary') and a dictionary containing all variants of words
# attained by deletion of single characters (see nidaba.lex.make_deldict).
lang_dicts:
  polytonic_greek: {dictionary: [dicts, greek.dic],
                    deletion_dictionary: [dicts, del_greek.dic]}
  latin: {dictionary: [dicts, latin.dic],
                    deletion_dictionary: [dicts, del_latin.dic]}

# Ocropus/kraken models
ocropus_models:
  greek: [models, omnibus-2014-05-31-10-16-00087000.pyrnn.gz]
  grc_teubner: [models, teubner-serif-2013-12-16-11-26-00067000.pyrnn.gz]
  atlantean: [models, atlantean.pyrnn.gz]
  fraktur: [models, fraktur.pyrnn.gz]
  fancy_ligatures: [models, ligatures.pyrnn.gz]

# Models solely working with kraken (i.e. models in HDF5 format).
kraken_models:
  default: [models, en-default.hdf5]


# List of plugins to load. Additional fields in the associative array will be
# handed over to the setup function of the plugin.  Be aware that plugins
# utilizing external components that aren't installed will cause nidaba to
# abort. 
plugins_load:
  tesseract: {implementation: capi, # set to either legacy (hOCR
                                              # output in an *.html file),
                                              # direct (hOCR output in an
                                              # *.hocr file), or capi
                                              # (tesseract version >= 3.02)
             tessdata: /cluster/tufts/perseus_ocr_code/tesseract/tessdata} # location of the tessdata
                                                 # path. May also be a storage
                                                 # tuple.
  #ocropus: {}
  kraken: {}
  #leptonica: {}
```

**Comment by mittagessen** [comment]
This happens when kraken can't load a model. I changed the behavior in the latest version (of kraken) to reraise the exception, causing a more helpful error message. You should verify your configuration and that the model file is situated under the given path.

**Comment by sonofmun** [comment]
From the way the config file is set up, I assumed that the models 
should be under $storage_path/models, i.e., 
/cluster/tufts/perseus_ocr/nidaba/OCR/models.  Is that incorrect?

On 13.08.2015 21:19, mittagessen wrote:
>
> This happens when kraken can't load a model. I changed the behavior in 
> the latest version (of kraken) to reraise the exception, causing a 
> more helpful error message. You should verify your configuration and 
> that the model file is situated under the given path.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenPhilology/nidaba/issues/6#issuecomment-130809728>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by mittagessen** [comment]
Thats correct.

**Comment by sonofmun** [comment]
Then perhaps the models that I downloaded from 
https://github.com/brobertson/ciaconna/tree/master/Classifiers are not 
compatible with Kraken?

On 14.08.2015 11:48, mittagessen wrote:
>
> Thats correct.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenPhilology/nidaba/issues/6#issuecomment-131052667>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by mittagessen** [comment]
I downloaded them myself yesterday and they work like a charm on my system here. Could you bump up the kraken to 0.4.6 using pip and record the error output? Alternatively you could try running kraken manually:

    kraken segment img.png lines.txt
    kraken ocr -m /path/to/model --lines lines.txt img.png

and see if that works.

**Comment by sonofmun** [comment]
So I reran with exactly the command above and got this error output in the celery log file:

```
[2015-08-17 05:33:26,110: ERROR/MainProcess] Task nidaba.ocr.kraken[5c9f00ab-dba0-48de-841d-01ee8bad195c] raised unexpected: IOError('Not a gzipped file',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 81, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 121, in ocr_kraken
    rnn = models.load_any(model)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/models.py", line 58, in load_any
    seq = load_pyrnn(fname)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/models.py", line 151, in load_pyrnn
    rnn = unpickler.load()
  File "/opt/shared/python/2.7.6/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/opt/shared/python/2.7.6/lib/python2.7/gzip.py", line 296, in _read
    self._read_gzip_header()
  File "/opt/shared/python/2.7.6/lib/python2.7/gzip.py", line 190, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file
```
Perhaps this means that the model file got corrupted somewhere along the way?  I will try redownloading it to see if that help.

**Comment by mittagessen** [comment]
Yeah it looks like you've downloaded a github HTML page instead of the actual file. Try cloning the whole repository and copying the file manually.

**Comment by sonofmun** [comment]
I feel stupid now.  I am in the process of cloning the repo now.

On 17.08.2015 11:48, mittagessen wrote:
>
> Yeah it looks like you've downloaded a github HTML page instead of the 
> actual file. Try cloning the whole repository and copying the file 
> manually.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenPhilology/nidaba/issues/6#issuecomment-131755606>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by sonofmun** [comment]
It is working now with the real models
