### ISSUE TITLE
Error: Invalid value for "--ocr" / "-o": Positional arguments are deprecated!

### ISSUE THREAD

**Issue by sonofmun** [OpenPhilology/nidaba#7]
When I use the following command to initialize a nidaba batch

    nidaba batch -b nlbin:threshold=0.5,zoom=0.5,escale=1.0,border=0.1,perc=80,range=20,low=5,high=90 -l tesseract -o kraken:greek -p spell_check:polytonic_greek phaistos/OCR/OGL/septuagint-dev/raw_ocr/hvd.swete.1.1901.kraken/*.pbm.png

I get the following error message:

```
Usage: nidaba batch [OPTIONS] FILES...

Error: Invalid value for "--ocr" / "-o": Positional arguments are deprecated!
```

Has something changed with the API?  This command worked without a problem before.
I am using nidaba 0.9.3 and kraken 0.4.2
You can check out my nidaba.yaml file on Homer at /home/mmunson/envs/nidaba/etc/nidaba/nidaba.yaml
This is also no longer working on the Tufts cluster where it worked before.

**Comment by mittagessen** [comment]
That's the other thing that changed with the API as resolving positional (*args) and keyword arguments (**kwargs) over a JSON-API seemed too error-prone. Just substitute -o kraken:model=greek for -o kraken:greek.

**Comment by sonofmun** [comment]
And I assume the same thing with -p?  I.e., it should be

     -p spell_check:model=polytonic_greek

On 27.10.2015 11:55, mittagessen wrote:
>
> That's the other thing that changed with the API as resolving 
> positional (/args) and keyword arguments (/*kwargs) over a JSON-API 
> seemed too error-prone. Just substitute -o kraken:model=greek for -o 
> kraken:greek.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenPhilology/nidaba/issues/7#issuecomment-151455305>.
>

-- 
Matthew Munson
Researcher
Alexander von Humboldt Chair of Digital Humanities
Universität Leipzig, Institut für Informatik
Augustusplatz 10, 04109 Leipzig
Deutschland

**Comment by sonofmun** [comment]
Neither 

    -p spell_check:model=polytonic_greek

nor 

    -p spell_check:dict=polytonic_greek

work.
What is the keyword to use with spell_check?

**Comment by sonofmun** [comment]
I figured it out.  I need the following:

    -p spell_check:language=polytonic_greek,filter_punctuation=False

I figured I should use filter_punctuation=False since that is the default in postprocessing.spell_check
